# Generated by Django 5.1.5 on 2025-02-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
