services:
  app:
    container_name: taberna
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./data/web:/vol/web
    env_file:
      - ./env/.env.dev
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: taberna-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./env/.env.dev.db

volumes:
   postgres-data:
