services:
  web:
    container_name: tb_django
    build:
      dockerfile: Dockerfile
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env/.env.dev
  db:
    image: postgres:15-alpine
    container_name: tb_postgres
    volumes:
      - tb_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.dev.db

volumes:
   tb_postgres_data:
