services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn shop.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - tbp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web



volumes:
  tbp_postgres_data:
  static_volume:
  media_volume:
