# Generated by Django 4.1.7 on 2023-04-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='social/avatars/avatar.png', upload_to='social/avatars/'),
        ),
    ]
