# Generated by Django 4.1.7 on 2023-05-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0003_friendshiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
    ]
