# Generated by Django 4.1.7 on 2023-05-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0004_profile_friends_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='social_profiles.profile'),
        ),
    ]
