# Generated by Django 4.1.7 on 2023-05-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0007_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='social_profiles.profile'),
        ),
    ]
