# Generated by Django 4.1.7 on 2023-05-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0008_alter_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
