# Generated by Django 4.1.7 on 2023-07-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0009_profile_posts_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
