# Generated by Django 5.0 on 2023-12-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0010_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(default=None, to='social_profiles.profile'),
        ),
    ]
