# Generated by Django 5.0.6 on 2024-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_profiles', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='people_you_may_know',
            field=models.ManyToManyField(to='social_profiles.profile'),
        ),
    ]
