# Generated by Django 5.0 on 2023-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='registration_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
