# Generated by Django 5.0.7 on 2024-08-26 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='portfolio/project_gallery/')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projectgallery', to='core.project')),
            ],
            options={
                'verbose_name': 'projectgallery',
                'verbose_name_plural': 'project gallery',
            },
        ),
    ]
