# Generated by Django 5.1.5 on 2025-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
    ]
