# Generated by Django 5.0.6 on 2024-07-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_friendrequest', 'New friendrequest'), ('accepted_friendrequest', 'Accepted friendrequest'), ('rejected_friendrequest', 'Rejected friendrequest'), ('post_like', 'Post like'), ('post_comment', 'Post comment'), ('chat_message', 'Chat message')], max_length=50),
        ),
    ]
